//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesManagementSouvenir_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHATLIEU
    {
        public CHATLIEU()
        {
            this.HANGs = new HashSet<HANG>();
        }
    
        public int MaChatLieu { get; set; }
        public string TenChatLieu { get; set; }
    
        public virtual ICollection<HANG> HANGs { get; set; }
    }
}
