//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesManagementSouvenir_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETHOADON
    {
        public int MaHD { get; set; }
        public int MaHang { get; set; }
        public int SoLuong { get; set; }
        public double DonGia { get; set; }
        public double GiamGia { get; set; }
        public decimal ThanhTien { get; set; }
    }
}
