//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesManagementSouvenir_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        public NHANVIEN()
        {
            this.HOADONs = new HashSet<HOADON>();
        }
    
        public int MaNV { get; set; }
        public string TaiKhoan { get; set; }
        public string MatKhau { get; set; }
        public string HoTenNV { get; set; }
        public string NgaySinh { get; set; }
        public string GioiTinh { get; set; }
        public string DiaChi { get; set; }
        public string Email { get; set; }
        public string CMND { get; set; }
        public string SDT { get; set; }
        public string AnhNV { get; set; }
        public string ChucVu { get; set; }
        public string NgayBDLV { get; set; }
        public Nullable<double> HeSoLuong { get; set; }
        public Nullable<double> Luong { get; set; }
    
        public virtual ICollection<HOADON> HOADONs { get; set; }
    }
}
